export const getCountryId = (countryName) => {
  const mapping = {
    "tanzania": "TZ",
    "nigeria": "NG",
    "uganda": "UG",
    "sudan": "SD",
    "united states": "US",
    "usa": "US",
    "madagascar": "MG",
    "united kingdom": "GB",
    "uk": "GB",
    "india": "IN",
    "cameroon": "CM",
    "cape verde": "CV",
    "republic of the congo": "CG",
    "mozambique": "MZ",
    "south africa": "ZA",
    "mali": "ML",
    "angola": "AO",
    "dr congo": "CD",
    "france": "FR",
    "kenya": "KE",
    "zambia": "ZM",
    "eritrea": "ER",
    "rwanda": "RW",
    "benin": "BJ",
    "senegal": "SN",
    "namibia": "NA",
    "guinea-bissau": "GW",
    "burkina faso": "BF",
    "morocco": "MA",
    "ethiopia": "ET",
    "malawi": "MW",
    "brazil": "BR",
    "tunisia": "TN",
    "somalia": "SO",
    "zimbabwe": "ZW",
    "egypt": "EG",
    "ghana": "GH",
    "western sahara": "EH",
    "australia": "AU",
    "china": "CN",
    "botswana": "BW",
    "burundi": "BI",
    "seychelles": "SC",
    "djibouti": "DJ",
    "south sudan": "SS",
    "lesotho": "LS",
    "são tomé and príncipe": "ST",
    "algeria": "DZ",
    "chad": "TD",
    "togo": "TG",
    "mauritania": "MR",
    "côte d'ivoire": "CI",
    "cote divoire": "CI",
    "liberia": "LR",
    "gambia": "GM",
    "mauritius": "MU",
    "swaziland": "SZ",
    "eswatini": "SZ",
    "sierra leone": "SL",
    "japan": "JP",
    "canada": "CA",
    "germany": "DE",
    "niger": "NE",
    "central african republic": "CF",
    "comoros": "KM"
  };
  return mapping[countryName.toLowerCase()] || null;
};

export const getCountryName = (countryId) => {
    const mapping = {
        "TZ": "Tanzania",
        "NG": "Nigeria",
        "UG": "Uganda",
        "SD": "Sudan",
        "US": "United States",
        "MG": "Madagascar",
        "GB": "United Kingdom",
        "IN": "India",
        "CM": "Cameroon",
        "CV": "Cape Verde",
        "CG": "Republic of the Congo",
        "MZ": "Mozambique",
        "ZA": "South Africa",
        "ML": "Mali",
        "AO": "Angola",
        "CD": "DR Congo",
        "FR": "France",
        "KE": "Kenya",
        "ZM": "Zambia",
        "ER": "Eritrea",
        "RW": "Rwanda",
        "BJ": "Benin",
        "SN": "Senegal",
        "NA": "Namibia",
        "GW": "Guinea-Bissau",
        "BF": "Burkina Faso",
        "MA": "Morocco",
        "ET": "Ethiopia",
        "MW": "Malawi",
        "BR": "Brazil",
        "TN": "Tunisia",
        "SO": "Somalia",
        "ZW": "Zimbabwe",
        "EG": "Egypt",
        "GH": "Ghana",
        "EH": "Western Sahara",
        "AU": "Australia",
        "CN": "China",
        "BW": "Botswana",
        "BI": "Burundi",
        "SC": "Seychelles",
        "DJ": "Djibouti",
        "SS": "South Sudan",
        "LS": "Lesotho",
        "ST": "São Tomé and Príncipe",
        "DZ": "Algeria",
        "TD": "Chad",
        "TG": "Togo",
        "MR": "Mauritania",
        "CI": "Côte d'Ivoire",
        "LR": "Liberia",
        "GM": "Gambia",
        "MU": "Mauritius",
        "SZ": "Eswatini",
        "SL": "Sierra Leone",
        "JP": "Japan",
        "CA": "Canada",
        "DE": "Germany",
        "NE": "Niger",
        "CF": "Central African Republic",
        "KM": "Comoros"
    };
    return mapping[countryId.toUpperCase()] || countryId;
};
